/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    AccountRecovery: () => import('#controllers/auth/account_recovery_controller'),
    Onboardings: () => import('#controllers/auth/onboardings_controller'),
    Register: () => import('#controllers/auth/register_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  Home: () => import('#controllers/home_controller'),
  Media: () => import('#controllers/media_controller'),
}
